### ISSUE TITLE
Перевод по СБП не работает

### ISSUE THREAD

**Issue by schtschenok** [AlexXanderGrib/node-qiwi-sdk#3]
Не получается сделать перевод через СБП. В истории платежей он отображается, но с "ошибкой платежа". Пробовал на разные банки - не выходит. Предположу, что либо я что-то не так делаю, либо они прикрыли API. В первом случае - скажу спасибо если проверите у себя и подтвердите, что у вас оно работает, а во втором случае - наверное стоит обновить документацию.

**Comment by AlexXanderGrib** [comment]
Скорее всего прикрыли. Для перевода теперь требуется ID операции, который я не знаю где достать

**Comment by AlexXanderGrib** [comment]
Точно прикрыли. 

```
███████╗
██╔════╝
█████╗░░
██╔══╝░░
██║░░░░░
╚═╝░░░░░
```
