### ISSUE TITLE
Не валидный amount fraction в ссылке на форму оплаты (метод createFormUrl).

### ISSUE THREAD

**Issue by KartoshkaPy** [AlexXanderGrib/node-qiwi-sdk#4]
Привет!
**Я использую qiwi-sdk и заметил, что генерируемый amount fraction всегда 0.**

Как я это делаю
```ts
static getPaymentLink(_amount: number, orderId: string): string {
  const amount = 1.1;

  // Why is amount fraction 0?
  return this.qiwi.createFormUrl(this.walletProvider, {
    amount,
    comment: orderId,
  });
}
``` 
Класс QiwiWallet можно найти тут:
https://github.com/Sweet-Coin-Market/Sweet-Coin-Market/blob/architecture-migration/src/services/wallets/QiwiWallet.ts

**Это действительно баг или я неправильно передаю amount?**

Почитал исходный код библиотеки, решил воспроизвести ситуацию в интерактивной консоли браузера.
![image](https://user-images.githubusercontent.com/59607313/132190734-bea520e5-1db9-4f6f-a662-a45638813690.png)
amountFraction действительно всегда 0.

Решил поэкспериментировать, убрал Math.round - почти все корректно
![image](https://user-images.githubusercontent.com/59607313/132191236-255e013c-be6d-4e34-b4d6-281c6d2bcf29.png)

Ещё поразмыслил, в итоге изменил код библиотеки:
![image](https://user-images.githubusercontent.com/59607313/132194841-904e7f88-e842-4ab7-8741-fe1cd3723ea7.png)

Всё работает!
![image](https://user-images.githubusercontent.com/59607313/132194566-db08a62b-6f0b-4f2e-a94a-d81505db2f3b.png)

***

Зависимости в package.json:
```json
"dependencies": {
    "module-alias": "^2.2.2",
    "mysql2": "^2.3.0",
    "node-vkcoinapi": "^1.8.0",
    "phone": "^3.1.6",
    "qiwi-sdk": "^1.7.2",
    "reflect-metadata": "^0.1.13",
    "sequelize": "^6.6.2",
    "sequelize-typescript": "^2.1.0",
    "vk-io": "^4.3.2",
    "vk-io-question": "^3.1.1"
  },
```
Только что обновил qiwi-sdk - проблема не решилась.

Спасибо!

**Comment by AlexXanderGrib** [comment]
Прошу прощение за игнор, я болел целый месяц поэтому на гитхаб редко заходил. Я понимаю что делать фикс для вас уже поздно, но всё равно спасибо, что сообщили о проблеме. Починю в ближайшее время

**Comment by AlexXanderGrib** [comment]
Фикс выпущен в версии `2.0.2`. Ещё раз благодарю за сообщение об этой ошибке

https://www.npmjs.com/package/qiwi-sdk/v/2.0.2
