### ISSUE TITLE
P2P.formatLifetime

### ISSUE THREAD

**Issue by Alex-146** [AlexXanderGrib/node-qiwi-sdk#6]
### первый баг связанный с `P2P.formatLifetime`
`@param days — Кол-во дней жизни счёта (может быть не целым числом)`
поскольку функция принимает число в сутках, необходимо получить значения в часах
(например 12 часов это половина, следовательно значение на вход равно 0.5)
```
const hours = 2
const value = hours / 24
P2P.formatLifetime(value)
```
генерирует форму со следующими данными
```
creationDateTime: '2021-11-16T19:37:07.788+03:00',
expirationDateTime: '2021-11-16T19:38:48+03:00',
```
разница в дате только 2 минуты вместо ожидаемых 2 часов

### второй баг (скорее всего проблема на стороне киви)
пользователь может оплатить просроченную форму, в браузере отображается надпись "Счет просрочен" но при получении статуса текущего счета будет "WAITING"

**Comment by AlexXanderGrib** [comment]
Скорее всего абсолютно все ошибки именно на стороне киви 
![Снимок экрана от 2021-11-22 02-53-17](https://user-images.githubusercontent.com/29816814/142784128-c8a18071-6cad-48b0-9f90-8781cc12604e.png)

**Comment by AlexXanderGrib** [comment]
Метод `formatLifetime()` устерел, теперь существуют `formatLifetimeDays()` и `formatLifetimeMinutes()`, они должны работать корректнее
